# Generated by Django 5.1 on 2024-10-26 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('autism_level', models.IntegerField()),
                ('avatar', models.CharField(max_length=255)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.parent')),
                ('therapists_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='therapists.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=255)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.child')),
            ],
        ),
        migrations.CreateModel(
            name='Pictogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=255)),
                ('arasaac_id', models.CharField(max_length=50)),
                ('arasaac_categories', models.CharField(max_length=255)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.collection')),
            ],
        ),
        migrations.CreateModel(
            name='PictogramUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_used', models.DateTimeField()),
                ('cant_used', models.IntegerField(default=0)),
                ('pictogra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.pictogram')),
            ],
        ),
    ]
