# Generated by Django 5.1 on 2024-10-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='child',
            new_name='child_id',
        ),
    ]
