# Generated by Django 5.1 on 2024-10-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='parent',
            new_name='parent_id',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='therapists',
            new_name='therapists_id',
        ),
    ]
