# Generated by Django 5.1 on 2025-03-27 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
        ('therapists', '0002_alter_therapist_document_back_validator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='therapists_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='therapists.therapist'),
        ),
    ]
