# Generated by Django 5.1 on 2024-09-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='pictogram',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='subcollection',
            old_name='image',
            new_name='image_url',
        ),
    ]
