# Generated by Django 5.1 on 2024-09-05 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_rename_image_collection_image_url_and_more'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='parents.parent'),
            preserve_default=False,
        ),
    ]
