# Generated by Django 5.1 on 2024-10-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_alter_child_avatar'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='therapists',
            field=models.ManyToManyField(blank=True, null=True, related_name='children_assigned', to='therapists.therapist'),
        ),
    ]
