# Generated by Django 5.1 on 2024-11-03 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_rename_child_collection_child_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictogramusage',
            name='child_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='child.child'),
        ),
        migrations.AlterField(
            model_name='pictogramusage',
            name='cant_used',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pictogramusage',
            name='date_used',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
