# Generated by Django 5.1 on 2024-11-03 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_pictogramusage_child_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictogramusage',
            old_name='pictogra_id',
            new_name='pictogram_id',
        ),
    ]
