# Generated by Django 5.1 on 2024-09-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_alter_child_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
