# Generated by Django 5.1 on 2024-11-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_rename_pictogra_id_pictogramusage_pictogram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictogramusage',
            name='cant_used',
            field=models.IntegerField(),
        ),
    ]
