# Generated by Django 5.1 on 2024-09-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_child_avatar'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='therapists',
            field=models.ManyToManyField(related_name='children_assigned', to='therapists.therapist'),
        ),
    ]
