# Generated by Django 5.1 on 2024-11-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_alter_pictogramusage_cant_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictogramusage',
            name='cant_used',
            field=models.IntegerField(default=0),
        ),
    ]
