# Generated by Django 5.1 on 2024-09-10 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0006_child_therapists'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictogramUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_used', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictogram_usages', to='child.child')),
                ('pictogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.pictogram')),
            ],
        ),
    ]
