# Generated by Django 5.1 on 2024-11-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0006_alter_pictogramusage_cant_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictogramusage',
            old_name='child_id',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='pictogramusage',
            old_name='pictogram_id',
            new_name='pictogram',
        ),
        migrations.AlterField(
            model_name='pictogramusage',
            name='cant_used',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pictogramusage',
            name='date_used',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='pictogramusage',
            unique_together={('child', 'pictogram')},
        ),
    ]
