# Generated by Django 5.1 on 2024-09-02 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileChild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('autism_level', models.IntegerField(choices=[(1, 'Level 1 - Requiring Support'), (2, 'Level 2 - Requiring Substantial Support'), (3, 'Level 3 - Requiring Very Substantial Support')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileParent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('Passport', 'Passport')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('document_number', models.CharField(max_length=50)),
                ('front_document_image', models.ImageField(blank=True, null=True, upload_to='documents/front/')),
                ('back_document_image', models.ImageField(blank=True, null=True, upload_to='documents/back/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileTherapist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('Passport', 'Passport')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('document_number', models.CharField(max_length=100)),
                ('front_document_image', models.ImageField(blank=True, null=True, upload_to='documents/front/')),
                ('back_document_image', models.ImageField(blank=True, null=True, upload_to='documents/back/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
