# Generated by Django 5.1 on 2025-03-14 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=255)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.child')),
            ],
            options={
                'db_table': 'child_collection',
            },
        ),
        migrations.CreateModel(
            name='Pictogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=255)),
                ('arasaac_id', models.CharField(max_length=50)),
                ('arasaac_categories', models.CharField(max_length=255)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecs.collection')),
            ],
            options={
                'db_table': 'child_pictogram',
            },
        ),
        migrations.CreateModel(
            name='PictogramUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_used', models.DateTimeField(auto_now=True)),
                ('cant_used', models.IntegerField(default=1)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='child.child')),
                ('pictogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecs.pictogram')),
            ],
            options={
                'db_table': 'child_pictogramusage',
                'unique_together': {('child', 'pictogram')},
            },
        ),
    ]
