# Generated by Django 5.1 on 2025-01-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('PASSPORT', 'Passport')], max_length=10)),
                ('document_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('document_front_validator', models.BooleanField(default=False)),
                ('document_back_validator', models.BooleanField(default=False)),
                ('firebase_id', models.CharField(max_length=30)),
            ],
        ),
    ]
