# Generated by Django 5.1 on 2025-02-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='document_back_validator',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='document_front_validator',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
